### ISSUE TITLE
Customer: Check in/ check out

### ISSUE THREAD

**Issue by ihill116** [ben145/HotelMotelHolidayInn#12]

**Comment by ihill116** [comment]
When done: After reserving room: Shows reserved room and option to check in is available

**Comment by bkeith20** [comment]
Got functions for check in and check out in Hotel, Room, and Customer. No user interface or interaction yet.
2 hours.

**Comment by bkeith20** [comment]
integrated with other code to fit project 0.5 hours

**Comment by bkeith20** [comment]
2 hours all done
