### ISSUE TITLE
Calendar reservation system

### ISSUE THREAD

**Issue by bkeith20** [ben145/HotelMotelHolidayInn#32]

**Comment by bkeith20** [comment]
Add time line for review. Reserve a room for a certain date range.

**Comment by bkeith20** [comment]
May reserve a room up to three years in advance.

**Comment by ekimmichmitchell** [comment]
create a reservation object

**Comment by ekimmichmitchell** [comment]
constructors and getters for object created

1hour

**Comment by ekimmichmitchell** [comment]
check rooms in hotel should also have the date and the stay durration

**Comment by ekimmichmitchell** [comment]
room hold onto dates that can't be booked because they are already reserved
2 hours
