### ISSUE TITLE
Customer: View rooms screen (command line)

### ISSUE THREAD

**Issue by csteel1** [ben145/HotelMotelHolidayInn#4]

**Comment by ihill116** [comment]
Screen that shows rooms organized neatly by room number
e.g. 
Room 3A: 2 queens, room service, minibar - $689
Room 3G: 1 twin, waterbed - $1000

**Comment by ihill116** [comment]
Testing: Run software on a list of rooms (text? or objects?). If the room screen shows them in the formatted order, it works.

**Comment by bkeith20** [comment]
format:
Room #: number and size of beds, other amenities, price

**Comment by bkeith20** [comment]
only shows available rooms

**Comment by ekimmichmitchell** [comment]
1 hour - prints out only the available rooms in order of room number
