### ISSUE TITLE
Customer/Employee: Log in

### ISSUE THREAD

**Issue by csteel1** [ben145/HotelMotelHolidayInn#5]

**Comment by ben145** [comment]
customer - reservation ID; if forgotten, email sent to provide ID (offer to reset?)
employee - employee ID
two separate classes, with different method abilities

**Comment by ben145** [comment]
Test

**Comment by ben145** [comment]
Time: 1.5 hours; Work done: constructor for customer w/ and w/out given parameters; tests made (lost)
