### ISSUE TITLE
Customer: Select a room to reserve

### ISSUE THREAD

**Issue by csteel1** [ben145/HotelMotelHolidayInn#6]

**Comment by MOOOoooD** [comment]
depends on #4
depends on #5
button/reserve - lists room info
no longer visible in list of avail rooms
maybe split between view room options and reserve room

Test view room -  select room, see room and amenities details, view alternate rooms
Test reserve - button to reserve

**Comment by MOOOoooD** [comment]
made two tests - need more - I created a generic inner room class so that I could see how the room could work, but mostly, I had to lookup some java functionality

**Comment by MOOOoooD** [comment]
Cannot test due to user input - hopefully this 'works'

**Comment by MOOOoooD** [comment]
need some help with integration with among the built classes - this coincides with card 15
